version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 